# Generated by Django 5.2 on 2026-05-10 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.AlterField(
            model_name='department',
            name='average_consultation_time',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='token',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_system.department'),
        ),
        migrations.AlterField(
            model_name='token',
            name='predicted_wait_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
